### ISSUE TITLE
keep Spiderfied does not apply when map is clicked.

### ISSUE THREAD

**Issue by HuaHub** [jawj/OverlappingMarkerSpiderfier#123] opened 2017-03-21 21:37 UTC
Is this the meaning? If so, how can I **always** keep the markers spiderfied?

Thx for the script.

**Comment by jawj** [comment] 2017-03-22 10:06
* The `keepSpiderfied` option at the moment, I think, only keeps the markers spiderfied when you click on one of the spiderfied markers.

* The markers *have* to be unspiderfied when you click on other markers, or change the zoom level, or things will go badly wrong.

* I think it would probably be harmless to allow markers to stay spiderfied when you click the map.

I'm closing this for now as intended behaviour, but I'll think about adding a new and separate option to keep markers spiderfied on map click.

**Closed by jawj** 2017-03-22 10:06 UTC

**Comment by HuaHub** [comment] 2017-03-22 19:20
Thank you for answering. Would it be a big effort to make the markers stay spiderfied on map click? I would greatly appreciate it.

**Comment by jawj** [comment] 2017-04-02 08:38
I've added an option for this to the newly-released version 1.0. Please let me know if you have any trouble with it.

**Comment by vurso** [comment] 2018-06-09 15:51
Hi I tried using that option but it doesn't seem to do anything (latest version of Google API) bear in mind this is all being hosted inside an ASPX WebForm so not the greatest start I know.

Ideally what I would like to do is to be view the map with all of the markers already spiderfied on the map so a user can see that there are for example 5 markers on this one same location (without the need for me to add custom marker SVG's).

Great product btw saved me a lot of crying lol.
